server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.171.128
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.171.128:3306/guli_cart
    username: root
    password: root
  task:
    execution:
      thread-name-prefix: cart-task-
      pool:
        core-size: 100
        max-size: 500
        keep-alive: 60s
        queue-capacity: 5000
        allow-core-thread-timeout: false
      shutdown:
        await-termination: true
        await-termination-period: 60
  rabbitmq:
    host: 192.168.171.128
    virtual-host: /lwx
    username: lwx123
    password: lwx123
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual
        concurrency: 4
feign:
  sentinel:
    enabled: true
ribbon:
  ReadTimeout: 300000
  ConnectTimeout: 300000
auth:
  jwt:
    pubKeyPath: E:\practice\rsa\rsa.pub
    cookieName: GMALL-TOKEN
    userKey: userKey
    expire: 15552000
mybatis-plus:
  global-config:
    db-config:
      id-type: auto

