server:
  port: 18088
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.171.128
  thymeleaf:
    cache: false
feign:
  sentinel:
    enabled: true
ribbon:
  ReadTimeout: 300000
  ConnectTimeout: 300000
threadPool:
  coreSize: 100
  maxSize: 500
  keepAliveTime: 60
  blockQueueSize: 5000
